#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom


mkdir ~/bin
PATH=~/bin:$PATH

# Download Repo itself
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo

# Make Repo executable
chmod a+x ~/bin/repo



# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -u git://github.com/crdroidandroid/android.git -b 11.0

# Clone local manifest! So that no need to manually git clone repos or change hals, you can use normal git clone or rm and re clone, they will cost little more time, and you may get timeout! Let's make it quit and depth=1 too.
git clone https://github.com/Apon77Lab/android_.repo_local_manifests.git --depth 1 -b aex .repo/local_manifests

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

git clone https://gitlab.com/Pranavkapoor001/device_asus_x00t.git device/asus/X00T

git clone https://gitlab.com/Pranavkapoor001/proprietary_vendor_asus.git vendor/asus

git clone https://gitlab.com/Pranavkapoor001/kernel_asus_sdm660.git kernel/asus/sdm660

